//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este portal concentra toda la información relativa a la industria de Tecnologías de la Información y Comunicaciones (TIC) generada en la región Noreste Argentino. .
        /// </summary>
        internal static string AboutSection_AboutContent {
            get {
                return ResourceManager.GetString("AboutSection_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portal NEA Tics.
        /// </summary>
        internal static string AboutSection_LeftColumn {
            get {
                return ResourceManager.GetString("AboutSection_LeftColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -  Programa SSICh - Ministerio de Industria, Empleo y Trabajo.
        /// </summary>
        internal static string AboutSection_Sponsor_SSICh {
            get {
                return ResourceManager.GetString("AboutSection_Sponsor_SSICh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las instituciones que llevaron adelante este proyecto:.
        /// </summary>
        internal static string AboutSection_SponsorsContent {
            get {
                return ResourceManager.GetString("AboutSection_SponsorsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sponsors.
        /// </summary>
        internal static string AboutSection_SponsorsLabel {
            get {
                return ResourceManager.GetString("AboutSection_SponsorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el portal encontrarán contenidos exclusivos para distintos perfiles del mundo TIC, tales como: empresas, emprendedores, estudiantes e invitados. .
        /// </summary>
        internal static string AboutSection_WhatToFindContent {
            get {
                return ResourceManager.GetString("AboutSection_WhatToFindContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qué encontrar.
        /// </summary>
        internal static string AboutSection_WhatToFindLabel {
            get {
                return ResourceManager.GetString("AboutSection_WhatToFindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca del Portal.
        /// </summary>
        internal static string AbuotSection_AboutLabel {
            get {
                return ResourceManager.GetString("AbuotSection_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su e-mail.
        /// </summary>
        internal static string ContactUsSection_EmailInput {
            get {
                return ResourceManager.GetString("ContactUsSection_EmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string ContactUsSection_EmailLabel {
            get {
                return ResourceManager.GetString("ContactUsSection_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string ContactUsSection_MessageLabel {
            get {
                return ResourceManager.GetString("ContactUsSection_MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su nombre.
        /// </summary>
        internal static string ContactUsSection_NameInput {
            get {
                return ResourceManager.GetString("ContactUsSection_NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string ContactUsSection_NameLabel {
            get {
                return ResourceManager.GetString("ContactUsSection_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el asunto del mensaje.
        /// </summary>
        internal static string ContactUsSection_SubjectInput {
            get {
                return ResourceManager.GetString("ContactUsSection_SubjectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string ContactUsSection_SubjectLabel {
            get {
                return ResourceManager.GetString("ContactUsSection_SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string ContactUsSection_SubmiButton {
            get {
                return ResourceManager.GetString("ContactUsSection_SubmiButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string ContactUsSecttion_LeftColumn {
            get {
                return ResourceManager.GetString("ContactUsSecttion_LeftColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño: &quot;Los #22&quot; - Desarrollo: &quot;Los implementadores&quot; ©Informatorio 2013.
        /// </summary>
        internal static string Footer_Development {
            get {
                return ResourceManager.GetString("Footer_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollador.
        /// </summary>
        internal static string Home_ProfileList_Developer {
            get {
                return ResourceManager.GetString("Home_ProfileList_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        internal static string Home_ProfileList_Enterprise {
            get {
                return ResourceManager.GetString("Home_ProfileList_Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        internal static string Home_ProfileList_Student {
            get {
                return ResourceManager.GetString("Home_ProfileList_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegí tu perfil.
        /// </summary>
        internal static string Home_ProfilesList {
            get {
                return ResourceManager.GetString("Home_ProfilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Informatorio es el Laboratorio de capacitaciones Informáticas de la Provincia del Chaco, un proyecto producto de la integración entre Universidad, Estado y Empresas dedicadas al desarrollo de Software y Servicios Informáticos..
        /// </summary>
        internal static string InformatorioSection_AboutContent {
            get {
                return ResourceManager.GetString("InformatorioSection_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué es?.
        /// </summary>
        internal static string InformatorioSection_AboutLabel {
            get {
                return ResourceManager.GetString("InformatorioSection_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail: informatoriochaco@gmail.com.
        /// </summary>
        internal static string InformatorioSection_ContactUsContent {
            get {
                return ResourceManager.GetString("InformatorioSection_ContactUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string InformatorioSection_ContactUsLabel {
            get {
                return ResourceManager.GetString("InformatorioSection_ContactUsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPERIENCIAS.
        /// </summary>
        internal static string InformatorioSection_ExperiencesButton {
            get {
                return ResourceManager.GetString("InformatorioSection_ExperiencesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GALERIA.
        /// </summary>
        internal static string InformatorioSection_GalleryButton {
            get {
                return ResourceManager.GetString("InformatorioSection_GalleryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informatorio Chaco.
        /// </summary>
        internal static string InformatorioSection_LeftColumn {
            get {
                return ResourceManager.GetString("InformatorioSection_LeftColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Informatorio tiene como objetivo primordial formar a los jóvenes en las competencias necesarias para ingresar a la industria creciente de Software y Servicios Informáticos de la Provincia del Chaco..
        /// </summary>
        internal static string InformatorioSection_ObjectivesContent {
            get {
                return ResourceManager.GetString("InformatorioSection_ObjectivesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        internal static string InformatorioSection_ObjectivesLabel {
            get {
                return ResourceManager.GetString("InformatorioSection_ObjectivesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenidos/Programa.
        /// </summary>
        internal static string InformatorioSection_ParticipateContent {
            get {
                return ResourceManager.GetString("InformatorioSection_ParticipateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participar.
        /// </summary>
        internal static string InformatorioSection_ParticipateLabel {
            get {
                return ResourceManager.GetString("InformatorioSection_ParticipateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROYECTOS.
        /// </summary>
        internal static string InformatorioSection_ProyectsButton {
            get {
                return ResourceManager.GetString("InformatorioSection_ProyectsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frondizi 174, Piso 4º, Edificio Bolsa de Comercio del Chaco. .
        /// </summary>
        internal static string InformatorioSection_RightColumn {
            get {
                return ResourceManager.GetString("InformatorioSection_RightColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madia Burgos (2013 - 2014).
        /// </summary>
        internal static string InformatorioSection_TeachersContent {
            get {
                return ResourceManager.GetString("InformatorioSection_TeachersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructores.
        /// </summary>
        internal static string InformatorioSection_TeachersLabel {
            get {
                return ResourceManager.GetString("InformatorioSection_TeachersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca.
        /// </summary>
        internal static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string MenuItem_ContactUs {
            get {
                return ResourceManager.GetString("MenuItem_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string MenuItem_Home {
            get {
                return ResourceManager.GetString("MenuItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informatorio.
        /// </summary>
        internal static string MenuItem_Informatorio {
            get {
                return ResourceManager.GetString("MenuItem_Informatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Polo IT Chaco.
        /// </summary>
        internal static string MenuItem_PoloITChaco {
            get {
                return ResourceManager.GetString("MenuItem_PoloITChaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué buscás?.
        /// </summary>
        internal static string MenuSearchBar {
            get {
                return ResourceManager.GetString("MenuSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué es un Polo Tecnológico?.
        /// </summary>
        internal static string PoloITChacoSection_AboutContent {
            get {
                return ResourceManager.GetString("PoloITChacoSection_AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué es?.
        /// </summary>
        internal static string PoloITChacoSection_AboutLabel {
            get {
                return ResourceManager.GetString("PoloITChacoSection_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail: contacto@polochaco.com.ar.
        /// </summary>
        internal static string PoloITChacoSection_ContactUsContent {
            get {
                return ResourceManager.GetString("PoloITChacoSection_ContactUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string PoloITChacoSection_ContactUsLabel {
            get {
                return ResourceManager.GetString("PoloITChacoSection_ContactUsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Polo IT Chaco.
        /// </summary>
        internal static string PoloITChacoSection_LeftColumn {
            get {
                return ResourceManager.GetString("PoloITChacoSection_LeftColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para participar: contacto@polochaco.com.ar.
        /// </summary>
        internal static string PoloITChacoSection_ParticipateContent {
            get {
                return ResourceManager.GetString("PoloITChacoSection_ParticipateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participar.
        /// </summary>
        internal static string PoloITChacoSection_ParticipateLabel {
            get {
                return ResourceManager.GetString("PoloITChacoSection_ParticipateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser un centro de referencia internacional en el desarrollo científico y la innovación tecnológica, siendo ejemplo concreto del Sistema Regional de Innovación, posicionando a la Región del Noreste Argentino en un lugar privilegiado..
        /// </summary>
        internal static string PoloITChacoSection_VisionContent {
            get {
                return ResourceManager.GetString("PoloITChacoSection_VisionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión.
        /// </summary>
        internal static string PoloITChacoSection_VisionLabel {
            get {
                return ResourceManager.GetString("PoloITChacoSection_VisionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        internal static string SliderFooter_EventsLabel {
            get {
                return ResourceManager.GetString("SliderFooter_EventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias.
        /// </summary>
        internal static string SliderFooter_NewsLabel {
            get {
                return ResourceManager.GetString("SliderFooter_NewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí se encuentran los datos para contactar a profesionales de la industria (diseñadores, desarrolladores/programadores freelance, etc.), empresas u organizaciones dedicadas a proveer productos y servicios de SSI, entidades educativas y organizaciones dedicadas al fomento de la industria informática..
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a También se encontrará información relevante como publicaciones descriptivas y explicativas del sector, datos de contactos, noticias referidas, entre otros..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de la Información.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingeniería de Software.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programación avanzada en Tecnologías:.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tecnologías .NET.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tecnologías Java.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tecnologías PHP.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resistencia, Chaco - Argentina.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LinkedIn:.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: --.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completa el forulario para dejarnos tu mensaje.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Luciano Escudero (2012 - 2013 - 2014).
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil: acceder.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: --.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gustavo Gimenez (2013 - 2014).
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil: acceder.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: --.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noelia Pinto (2012 - 2013 - 2014).
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil: acceder.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: acceder        Diego Ramirez (2014).
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LinkedIn:.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un poco de historia..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile: --.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: --.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gilda R. Romero (2013 - 2014).
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil: acceder.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: acceder.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Darío Vallejos (2012 - 2013 - 2014).
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil: acceder.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: --.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un Polo Tecnológico es un conjunto de industrias tecnológicas, generalmente acompañadas de instituciones educativas y de investigación, situadas en una ubicación física común..
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El principal objetivo de un Polo Tecnológico es acercar las universidades y la industria para fomentar el desarrollo de soluciones locales con tecnología de punta, aportando conocimientos y generando nuevas oportunidades de trabajo para el capital humano regional..
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comisión de Recursos Humanos, surgida a partir del 1er Foro de Competitividad de  la Industria de Software y Servicios Informáticos (SSI) del Chaco, llevado a cabo en los años 2009 y 2010, determinó la creación de un espacio para el crecimiento y la especialización del capital humano en la Industria SSI..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El modelo conceptual parte de la ideología del tradicional vínculo Universidad-Empresa-Gobierno, denominado académicamente Triángulo de Sábato y, actualmente, se ha extendido a la filosofía Sistema Regional de Innovación..
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook: PoloITChaco.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: PoloITChaco.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Polo Tecnológico Chaco ha sido formado y ubicado en un área estratégicamente localizada y desarrollada, en pos de ofrecer un entorno de prestigio para atraer a empresas, en general, de alta tecnología, tecnologías emergentes o de punta..
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La figura del Polo Tecnológico promueve una colaboración implícita y explícita entre los agentes económicos locales y/o regionales en primer término y, nacionales y extranjeros en segundo término..
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el año 2011, se convocó al Polo Tecnológico Chaco, la entidad representante de la industria de Tecnologías de la Información y Comunicaciones (TIC), a la Universidad Tecnológica Nacional - Facultad Regional Resistencia (UTN - FRRe) y, a la Empresa Sistemas Globales S.A. (Globant) para  avanzar en la creación del Laboratorio Informático del Chaco. Al año siguiente, se dió inicio al 1er ciclo del “Curso de Desarrollo Avanzado de aplicaciones Informáticas”..
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook: informatorio.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter: N/A.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Curso de Desarrollo Avanzado de Aplicaciones Informáticas contempla los siguientes Módulos:.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fundamentos de la programación.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
